### ISSUE TITLE
Snapchat Icon

### ISSUE THREAD

**Issue by Eldog02** [lucaburgio/iconoir#10]
Yep, another social media icon, brilliant. A Snapchat icon would allow me to complete the suite of social media links for a site I'm designing with only Iconoir icons.

Thanks for taking time to make these icons!

**Comment by lucaburgio** [comment]
added in 71b48ce

**Comment by lucaburgio** [comment]
Found an issue with Snapchat icon from pull-request. Re-opening the issue as reminder.

**Comment by lucaburgio** [comment]
Added 9368512
