### ISSUE TITLE
[FEAT] Release React Library

### ISSUE THREAD

**Issue by filipposarzana** [lucaburgio/iconoir#107]
**Is your feature request related to a problem? Please describe.**
Some icons are missing from React Library as unreleased like `PageEdit` and latest release is `v2.1.0`

**Comment by paescuj** [comment]
I'm going to make a new release as soon as possible...

**Comment by lucaburgio** [comment]
@paescuj Following this, could you DM me? I would like to ask you a couple of things about the React version and NPM if you have the time. Twitter DM here https://twitter.com/burgioluca or let me know if you prefer something else 🙌

**Comment by paescuj** [comment]
@lucaburgio Sure, I will contact you this weekend! (No time atm 😢)

**Comment by filipposarzana** [comment]
@paescuj Any update on this?

**Comment by lucaburgio** [comment]
Solved with #131
