### ISSUE TITLE
[FEAT] How do I change the icon color using the stylesheet import?

### ISSUE THREAD

**Issue by TomasKostadinov** [lucaburgio/iconoir#120]
**Is your feature request related to a problem? Please describe.**
As per your Readme it is possible to use the library via a simple stylesheet import:

```
Import the CSS File:

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lucaburgio/iconoir@master/css/iconoir.css">

Here is an example in HTML:

<i class="iconoir-hand-brake"></i>

The class must always be "iconoir-" and then the name of the icon. You can find the names of the icons here.
```

**Describe the solution you'd like**
I'd like to be able to change the icon's color.

**Describe alternatives you've considered**
I tried changing background and text color of the items but that did not work. How is it intended to change the background color of the icons using the css import method?

**Additional context**
I'm currently working on an Angular project and unfortunately this seems to be the only way to use your library.

**Comment by xbauquet** [comment]
Hi,
I have the same issue in my project.
I found a work around with a complex filter looking something like that for the color red:
`  
filter: invert(24%) sepia(95%) saturate(7448%) hue-rotate(358deg) brightness(96%) contrast(116%);
`

You can find a generator behind this url:  https://codepen.io/sosuke/pen/Pjoqqp
It looks like you can also use this npm package: https://github.com/willmendesneto/hex-to-css-filter#usage
