### ISSUE TITLE
Searchbar is lagging/stopping

### ISSUE THREAD

**Issue by JohnDominicJasmin** [lucaburgio/iconoir#121]
Search bar is lagging and stopping while searching for something, I'm currently using brave browser

**Comment by sammarks** [comment]
@lucaburgio I would be happy to help with this if you publish the website source as a repository! I know that might be difficult with the donate button being there etc, but figured I would offer.

**Comment by lucaburgio** [comment]
@sammarks It's not on GitHub at the moment, but I'll consider it for sure 👍

**Comment by lucaburgio** [comment]
It should be fixed now @JohnDominicJasmin. Checked on Brave too.
We can still improve that anyway 🙌
