### ISSUE TITLE
Amenities bundle.

### ISSUE THREAD

**Issue by emberhood** [lucaburgio/iconoir#122]
Greetings, I would like to request a bundle of amenities icons. Here is a list of it.

- Towels / pillows ![image](https://user-images.githubusercontent.com/57503486/151345532-874da0b3-8cbe-4a8c-b91d-04b8bc7267d9.png)
- Bed linens ![image](https://user-images.githubusercontent.com/57503486/151346647-1f3d76a7-4244-48c4-baf6-f206dff3b44d.png)
- Iron ![image](https://user-images.githubusercontent.com/57503486/151345602-85ca939b-b405-4617-acad-804bdd9b55d5.png)
- Fireplace ![image](https://user-images.githubusercontent.com/57503486/151345725-03bffd13-c6d8-47e7-833e-a24caf26b4b6.png)
- Heating ![image](https://user-images.githubusercontent.com/57503486/151345786-b0819653-62c4-4f90-943e-e5629c1c67fd.png)
- Cooling ![image](https://user-images.githubusercontent.com/57503486/151345814-d51eae7b-f7b6-491a-a261-fe384e368a37.png)
- First Aid Kit ![image](https://user-images.githubusercontent.com/57503486/151346781-10418cf7-273e-497a-8131-f06e9ff636af.png)
- Elevator ![image](https://user-images.githubusercontent.com/57503486/151345930-d0c31dff-a17e-4ffe-92a6-c2cb66866cb7.png)
- Hairdryer ![image](https://user-images.githubusercontent.com/57503486/151346057-c0194ca9-2ca0-438a-9076-1ea4b7e83d45.png)
- Oven ![image](https://user-images.githubusercontent.com/57503486/151346100-f2a9b8e7-d87b-46f4-bc8f-38d0e9621720.png)
- Microwave ![image](https://user-images.githubusercontent.com/57503486/151347191-d510dfd5-d612-49ca-9a55-c01d6b87c9fc.png)
- Toaster ![image](https://user-images.githubusercontent.com/57503486/151347248-33eaf915-151d-44e1-bebe-5565d2b43773.png)
- Stove ![image](https://user-images.githubusercontent.com/57503486/151346134-3c9d160c-c4ac-4aab-9d34-6718fc7f6086.png)
- Dishwasher ![image](https://user-images.githubusercontent.com/57503486/151347322-1e4f447c-6b6b-4846-89d6-6b9840eb4df8.png)
- Fire Extinguisher ![image](https://user-images.githubusercontent.com/57503486/151346194-e840fbd0-c697-4859-b6d5-026db5071d97.png)
- Pool ![image](https://user-images.githubusercontent.com/57503486/151347407-faf4577d-f32e-4914-bb45-26f23a4e800a.png)
- Hangers ![image](https://user-images.githubusercontent.com/57503486/151346325-9782d219-3e60-4163-884e-07d0ccbfc40c.png)
- Shampoo ![image](https://user-images.githubusercontent.com/57503486/151346288-efc59247-eda0-475f-9d29-7f9ef0a1c118.png)
- Shower gel ![image](https://user-images.githubusercontent.com/57503486/151346577-7562a0e0-ff46-4a53-82bc-20a4f300e518.png)
- Dishes and silverware ![image](https://user-images.githubusercontent.com/57503486/151346401-52bc4ba4-6aff-4c61-9de7-d0342ffa83ba.png)
- Coffee maker ![image](https://user-images.githubusercontent.com/57503486/151346435-918febc8-8298-412f-a64e-a1bf69cef687.png)
- BBQ ![image](https://user-images.githubusercontent.com/57503486/151347628-90801de8-b896-4af0-9b11-5026e27fdf14.png)
- Private entrance ![image](https://user-images.githubusercontent.com/57503486/151346492-67ea27ae-3a84-4be2-b1b4-2330d093ae98.png)
- Balcony ![image](https://user-images.githubusercontent.com/57503486/151346848-67a63964-cab7-4d1c-b17d-a3644f140ba2.png)
- Pets allowed ![image](https://user-images.githubusercontent.com/57503486/151346882-79868eb1-5bda-44b8-9593-486bc2c35b8c.png)
- Crib ![image](https://user-images.githubusercontent.com/57503486/151346708-b126e5d7-0c18-450b-bccb-accf990f07c2.png)

**Comment by lucaburgio** [comment]
Could you split them into different requests? @emberhood
Thank you!
