### ISSUE TITLE
[ICON] Gamepad icon

### ISSUE THREAD

**Issue by SixBeeps** [lucaburgio/iconoir#125]
## Icon Request

* Icon name: Gamepad Controller
* Use case: Projects relating to video games or video game consoles
* Screenshots of similar icons: Something like this: ![Gamepad icon](https://www.svgrepo.com/show/57965/gamepad.svg)

**Comment by juanpass** [comment]
WhatsApp

**Comment by SixBeeps** [comment]
> WhatsApp

Hey @juanpass not sure if you realized, but you should make a separate issue for your own icon requests.
