### ISSUE TITLE
Tailwind Icon Color 

### ISSUE THREAD

**Issue by nilsvennemann** [lucaburgio/iconoir#126]
When you use TailwindCSS you cant change the Color with `text-blue-600`. Please Fix it!

**Comment by lucaburgio** [comment]
@nilsvennemann Could add more info and describe your process?

**Comment by nilsvennemann** [comment]
You can't make text-red-600 as example the icon don't change the color

**Comment by sammarks** [comment]
@nilsvennemann are you using the React package, or are you just using the CSS styles?

**Comment by nilsvennemann** [comment]
Css Style

**Comment by paescuj** [comment]
This is a duplicate of #120. Technically, it's not possible to change the color at the moment. I can take a look at this over the next week!
