### ISSUE TITLE
[ICON] Ellipsis

### ISSUE THREAD

**Issue by HankTech** [lucaburgio/iconoir#137]
## Icon Request

* Icon name: Elipsis
* Use case: menu
* Screenshots of similar icons:
[https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Simple_icon_ellipsis.svg/1280px-Simple_icon_ellipsis.svg.png](url)
[https://icon-library.com/images/ellipsis-icon/ellipsis-icon-3.jpg](url)

**Comment by lucaburgio** [comment]
Already available as `more-horiz` and `more-vert`
