### ISSUE TITLE
[FEAT] Update peerDependecies to include React 18

### ISSUE THREAD

**Issue by gcavancer** [lucaburgio/iconoir#147]
Currently, peerDependencies does not list React 18. If your own dependencies are compatible, would it be possible to publish a new version including React 18?

**Comment by sammarks** [comment]
@lucaburgio this has already been updated, so we just need to create a new release and it should automatically publish to NPM.

**Comment by Guirdo** [comment]
Please, release it!

**Comment by lucaburgio** [comment]
Pardon, I was away for a while. I'm going to create a new minor release right now for this 🙌

**Comment by lucaburgio** [comment]
Version published https://github.com/lucaburgio/iconoir/releases/tag/v4.9.2
