### ISSUE TITLE
Use descriptive names for icon alternatives

### ISSUE THREAD

**Issue by kwangure** [lucaburgio/iconoir#15]
The title says it all. For example, instead of `edit-2`, consider renaming the icon to `edit-underlined`.
![Screenshot 2021-05-13 at 11 13 21 pm](https://user-images.githubusercontent.com/20745107/118182048-35989c80-b441-11eb-8a59-a8fbc2ed9e15.png)

Insead of `albums-1` and `album-2`, consider renaming the `album-1` to something like `albums-layered` and `album-2` to something like `albums-line`.
![Screenshot 2021-05-13 at 11 21 03 pm](https://user-images.githubusercontent.com/20745107/118182645-ed2dae80-b441-11eb-98f7-e46b8d062fd9.png)

Numbered icon names are difficult to remember, forcing you to keep visiting documentation to remember which one was which. As an example, see [Material Design Icons](https://materialdesignicons.com/) for ideas for alternative-icon naming conventions. They have a consistent naming convention for alternatives.

**Comment by lucaburgio** [comment]
Fixed fc85250
