### ISSUE TITLE
Remove Pin

### ISSUE THREAD

**Issue by Arvid-ctrl** [lucaburgio/iconoir#151]
## Icon Request

* Icon name: "unpin"
* Use case: "removing a pin that was set before"
* Screenshots of similar icons: 
![grafik](https://user-images.githubusercontent.com/77011980/170255067-26a1c21d-3b3d-4123-8c1f-91e8e43dc9ea.png)

**Comment by Arvid-ctrl** [comment]
didn't see any icon and / or requests for that ... hopefully I am not blind xD

**Comment by Arvid-ctrl** [comment]
![Pin-1](https://user-images.githubusercontent.com/77011980/170258413-6c704368-6e0b-4b22-8973-972afd11f601.svg)
![Pin](https://user-images.githubusercontent.com/77011980/170258416-fe333962-5a84-43e2-96d3-574ed6aca568.svg)

Suggestions

**Comment by lucaburgio** [comment]
👋 Thank you for the suggestion. We have a pin icon but not the remove-pin icon, I'll add it as soon as possible 🙌
