### ISSUE TITLE
157 Icons using `stroke="black"` instead of `stroke="currentColor"`

### ISSUE THREAD

**Issue by PianoManDanDan** [lucaburgio/iconoir#17]
## Prerequisites

* Version: 4.2.2
* Are you running from source/master: Yes
* Are you using a released build: Yes

## Issue

Trying to change the color of any of the icons that have `stroke="black"` in them with css won't work as the stroke setting  overwrites any styles you try and apply to the icon. To change the color you'd have to manually edit the files.

## Additional info or screenshots

The following is a list of all icons that have `stroke="black"` in them:

* icons\1st-medal.svg
* icons\accessibility-sign.svg
* icons\accessibility-tech.svg
* icons\accessibility.svg
* icons\add-database-script.svg
* icons\add-frame.svg
* icons\airplane-helix-45deg.svg
* icons\airplane-helix.svg
* icons\airplane-rotation.svg
* icons\antenna-signal-rounded.svg
* icons\app-notification.svg
* icons\apple-imac-2021-side.svg
* icons\apple-imac-2021.svg
* icons\apple-swift.svg
* icons\ar-symbol.svg
* icons\basketball-field.svg
* icons\bell-notification.svg
* icons\bluetooth-rounded.svg
* icons\bowling-ball.svg
* icons\box-iso.svg
* icons\boxing-glove.svg
* icons\cable-rounded.svg
* icons\codepen.svg
* icons\control-slider.svg
* icons\cycling.svg
* icons\database-backup.svg
* icons\database-export.svg
* icons\database-monitor.svg
* icons\database-restore.svg
* icons\database-rounded.svg
* icons\database-script.svg
* icons\database-settings.svg
* icons\database-stats.svg
* icons\design-pencil.svg
* icons\drag-hand-gesture.svg
* icons\dribbble.svg
* icons\euro-square.svg
* icons\ev-charge-alt.svg
* icons\ev-charge.svg
* icons\ev-plug-charging.svg
* icons\ev-plug-error.svg
* icons\ev-plug.svg
* icons\ev-rounded.svg
* icons\ev-station.svg
* icons\face-id.svg
* icons\farm.svg
* icons\filter-alt.svg
* icons\finder.svg
* icons\Fishing.svg
* icons\flower.svg
* icons\frame-select.svg
* icons\frame-simple.svg
* icons\frame.svg
* icons\fx-rounded.svg
* icons\fx.svg
* icons\garage.svg
* icons\gas-tank-drop.svg
* icons\gas-tank.svg
* icons\hand-brake.svg
* icons\hat.svg
* icons\hexagon-alt.svg
* icons\high-priority.svg
* icons\home-simple-door.svg
* icons\home-simple.svg
* icons\hospital.svg
* icons\industry.svg
* icons\ios-settings.svg
* icons\leaderboard-star.svg
* icons\leaderboard.svg
* icons\load-action-floppy.svg
* icons\lock-key.svg
* icons\mac-control-key.svg
* icons\mac-option-key.svg
* icons\mac-os-window.svg
* icons\map-issue.svg
* icons\maps-arrow-issue.svg
* icons\maps-go-straight.svg
* icons\maps-turn-back.svg
* icons\maps-turn-left.svg
* icons\maps-turn-right.svg
* icons\medal.svg
* icons\megaphone.svg
* icons\mouse-button-left.svg
* icons\mouse-button-right.svg
* icons\multi-mac-os-window.svg
* icons\multi-window.svg
* icons\off-rounded.svg
* icons\oil-industry.svg
* icons\on-rounded.svg
* icons\one-finger-select-hand-gesture.svg
* icons\open-in-browser.svg
* icons\open-in-window.svg
* icons\open-select-hand-gesture.svg
* icons\pc-mouse.svg
* icons\pen-connect-bluetooth.svg
* icons\pen-connect-wifi.svg
* icons\pen-tablet-connect-usb.svg
* icons\pen-tablet-connect-wifi.svg
* icons\pen-tablet.svg
* icons\people-rounded.svg
* icons\pocket.svg
* icons\priority-down.svg
* icons\priority-up.svg
* icons\receive-dollars.svg
* icons\receive-euros.svg
* icons\receive-pounds.svg
* icons\receive-yens.svg
* icons\reminder-hand-gesture.svg
* icons\remove-database-script.svg
* icons\remove-frame.svg
* icons\reports.svg
* icons\running.svg
* icons\save-action-floppy.svg
* icons\save-floppy-disk.svg
* icons\scale-frame-enlarge.svg
* icons\scale-frame-reduce.svg
* icons\scale-frame.svg
* icons\send-dollars.svg
* icons\send-euros.svg
* icons\send-pounds.svg
* icons\send-yens.svg
* icons\settings-cloud.svg
* icons\settings-profiles.svg
* icons\single-tap-gesture.svg
* icons\skateboard.svg
* icons\skateboarding.svg
* icons\spock-hand-gesture.svg
* icons\stretching.svg
* icons\style-border.svg
* icons\swipe-down-gesture.svg
* icons\swipe-left-gesture.svg
* icons\swipe-right-gesture.svg
* icons\swipe-two-fingers-down-gesture.svg
* icons\swipe-two-fingers-left-gesture.svg
* icons\swipe-two-fingers-right-gesture.svg
* icons\swipe-two-fingers-up-gesture.svg
* icons\swipe-up-gesture.svg
* icons\system-restart.svg
* icons\system-shut.svg
* icons\terminal-simple.svg
* icons\treadmill.svg
* icons\trekking.svg
* icons\trophy.svg
* icons\tunnel.svg
* icons\twitter-verified-badge.svg
* icons\verified-badge.svg
* icons\verified-user.svg
* icons\view-columns-3.svg
* icons\vr-symbol.svg
* icons\waist.svg
* icons\walking.svg
* icons\web-window-close.svg
* icons\web-window-energy-consumption.svg
* icons\web-window.svg
* icons\wifi-rounded.svg
* icons\yen-square.svg
* icons\yoga.svg

**Comment by lucaburgio** [comment]
Thank you, Daniel. It's in the queue. Will work on it soon.

**Comment by lucaburgio** [comment]
Fixed on 2131ef7
