### ISSUE TITLE
Fonts CSS

### ISSUE THREAD

**Issue by creativeDM** [lucaburgio/iconoir#20]
I am using fonts into my css - copy and paste the code you share for font - is there any iconoir.css like font-awesome.css which is included ::before content:"\abcs" like that???
Icons are awesome, It will popular in some time, but you need to add fonts css first to make it complete usable
Pls help

Thanks!

**Comment by lucaburgio** [comment]
Hi, you can use the any font in the folder **_/fonts_**, here is an example of usage:

HTML
`<span class="iconoir-hand-brake"></span>`

CSS
`.iconoir-hand-brake:before {
  content: "\e900";
}`

**Comment by ganigeorgiev** [comment]
I think @creativeDM was asking for a css file with class-icon mapping, such as https://github.com/mono-company/mono-icons/blob/master/iconfont/icons.css.

@lucaburgio Could you provide a css file for that?

**Comment by Wiwaltill** [comment]
Hey everyone! 
I took the time to create a CSS file for Iconoir. This can easily be included in the HTML file!
The CSS file can also be used in the GitHub project.
Best Regards

[iconoir.css.zip](https://github.com/lucaburgio/iconoir/files/6720197/iconoir.css.zip)

@lucaburgio @creativeDM @ganigeorgiev

**Comment by lucaburgio** [comment]
Hey @Wiwaltill , thank you for the help! Feel free to open a pull request with the CSS file in the `fonts` folder and include a small brief in the readme file, under `Font`. Please also add a small summary of the process you used and if there are specific rules for that.

Recently, I was considering pausing the support for the fonts until we find a good and reasonable solution for the maintenance and future updates. If you want to keep supporting this file, I would be happy to have an updated CSS of the library 🙌

**Comment by Wiwaltill** [comment]
@lucaburgio 
Thanks for the feedback.
I can take care of the CSS file with pleasure. I just need to know which icons have been added.

**Comment by lucaburgio** [comment]
🎉 If you are aligned with the current v.4.3.1 you're good to go.

**Comment by Wiwaltill** [comment]
Yes, of course. This is the version I used. 
I only spoke already for the future. In case there are new icons that need to be added.

**Comment by Wiwaltill** [comment]
Update for @lucaburgio:
I have created the file and updated the README. Can now be accepted as a pull request.
