### ISSUE TITLE
Two Cart Icons On Website

### ISSUE THREAD

**Issue by phultquist** [lucaburgio/iconoir#21]
## Step to reproduce

Visit [website](https://iconoir.com)
Search for "cart"
See two carts

## Additional info or screenshots

<img src="https://i.ibb.co/kGkrQrj/188702606-1440547199639036-477620600432039548-n.png" alt="188702606-1440547199639036-477620600432039548-n" border="0">

**Comment by lucaburgio** [comment]
Thank you for spotting this! Solved ✅
