### ISSUE TITLE
React alternative

### ISSUE THREAD

**Issue by lekoala** [lucaburgio/iconoir#23]
Hi!

Great work with these icons they look really good.

I wanted to add a humble suggestion for those who need a component and don't want to use react. I recently created a custom element to work with various icon libraries

https://github.com/lekoala/last-icon

Just added the support for your icon set :-)

Keep up the good work!

**Comment by lucaburgio** [comment]
Glad you like them, if you want to contribute to the library feel free to add a similar .js template for iconoir here to support the project!
