### ISSUE TITLE
Windows, Linux and macOS icons

### ISSUE THREAD

**Issue by saenzramiro** [lucaburgio/iconoir#24]
## Icon Request

* Icon name: windows, linux, macos
* Use case: Commonly used in websites of desktop apps
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/2694669/119141650-e7286680-ba1b-11eb-80bf-4c1f78129730.png)
![image](https://user-images.githubusercontent.com/2694669/119141846-26ef4e00-ba1c-11eb-866b-2bf739613629.png)
![image](https://user-images.githubusercontent.com/2694669/119141861-2c4c9880-ba1c-11eb-9df2-2cdd4117856b.png)

**Comment by lucaburgio** [comment]
Added 9368512
