### ISSUE TITLE
Media Icon

### ISSUE THREAD

**Issue by fusepilot** [lucaburgio/iconoir#33]
* Icon name: Media
* Use case: To represent "media". The camera icon is somewhat appropriate for photos, but not so much for non-camera-generated images. The media icon is ambiguous enough to represent both.
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/187164/119467838-c2bdda00-bcfa-11eb-90aa-3d2ce3d69d1c.png)![image](https://user-images.githubusercontent.com/187164/119467874-cbaeab80-bcfa-11eb-9eec-cc048d180c68.png)![image](https://user-images.githubusercontent.com/187164/119467907-d406e680-bcfa-11eb-8a74-980b8b6bf509.png)

Was going to make a PR, but see you're not accepting them at the moment. I'll attach it here in case you find it useful.

[media.svg.zip](https://github.com/lucaburgio/iconoir/files/6537867/media.svg.zip)

**Comment by lucaburgio** [comment]
Added 9368512
