### ISSUE TITLE
eye-close is upside down

### ISSUE THREAD

**Issue by kluplau** [lucaburgio/iconoir#36]
Version: 4.3.0
Are you running from source/master: Website
Are you using a released build: N/A
Operating system: N/A
Bits: N/A

How it looks now
![image](https://user-images.githubusercontent.com/1536598/119624459-77462180-be09-11eb-972b-97635ee67ce2.png)

How it should look
![image](https://user-images.githubusercontent.com/1536598/119624564-95ac1d00-be09-11eb-89b5-102178d48a7d.png)

You only see the upper eye lid when eyes are closed, which is why it should be rotated 180deg.

Other than that, it's a STELLAR icon lib. Well done.

**Comment by lucaburgio** [comment]
Thank you for spotting this! I'll fix it soon

**Comment by lucaburgio** [comment]
Fixed in 0cc5bfb
