### ISSUE TITLE
Icons that use `fill="black"` will always have that area filled in black as opposed to the current color

### ISSUE THREAD

**Issue by PianoManDanDan** [lucaburgio/iconoir#39]
## Prerequisites

* Version: 4.3.0
* Are you running from source/master: Yes
* Are you using a released build: Yes
* Operating system: 

## Step to reproduce

Try to change the color of any of the affected icons using CSS/the "color" prop of the react library icons.

### Actual behavior

Part of the affected icons remains black despite changing the icon's color. (Attached image is only one example)
![image](https://user-images.githubusercontent.com/32208138/120245969-c60b1580-c266-11eb-8933-7aced665f9cd.png)

## Additional info or screenshots

Icons using `fill="black"` are:

* icons\accessibility-tech.svg
* icons\accessibility.svg
* icons\bowling-ball.svg
* icons\box-iso.svg
* icons\cart-alt.svg
* icons\cart.svg
* icons\cloud-desync.svg
* icons\cloud-sync.svg
* icons\emoji-blink-left.svg
* icons\emoji-blink-right.svg
* icons\emoji-sad.svg
* icons\emoji.svg
* icons\mac-dock.svg
* icons\mouse-scroll-wheel.svg
* icons\no-credit-card.svg
* icons\page-search.svg
* icons\page-star.svg
* icons\people-rounded.svg

**Comment by lucaburgio** [comment]
Fixed in 1c21eac

**Comment by lucaburgio** [comment]
Also, `cloud-sync` and `cloud-desync` were affected by an issue during the SVG export. Fixed in 426f51c
