### ISSUE TITLE
[ICON] Piggy bank

### ISSUE THREAD

**Issue by carlfredrikhero** [lucaburgio/iconoir#43]
## Icon Request

* Icon name: Piggy bank
* Use case: Save money in general, discounted prices in e-commerce 
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/1053167/120548148-4f028800-c3f2-11eb-943f-c7ecd6430e91.jpeg)

**Comment by lucaburgio** [comment]
Added 9368512
