### ISSUE TITLE
[ICON] Parking

### ISSUE THREAD

**Issue by smessaris** [lucaburgio/iconoir#46]
## Icon Request

* Icon name: Parking
* Use case: Apartment Feature List for Rentals
* Screenshots of similar icons:
![Screen Shot 2021-06-03 at 15 14 22](https://user-images.githubusercontent.com/61061455/120643095-68511600-c47e-11eb-8eb9-7aa6e494891d.png)

**Comment by lucaburgio** [comment]
Added 9368512
