### ISSUE TITLE
[ICON] Air conditioner

### ISSUE THREAD

**Issue by smessaris** [lucaburgio/iconoir#47]
## Icon Request

* Icon name: Air conditioner
* Use case: Apartment Feature List for Rentals
* Screenshots of similar icons:
![Screen Shot 2021-06-03 at 15 17 08](https://user-images.githubusercontent.com/61061455/120643402-cc73da00-c47e-11eb-9839-29585f16da05.png)

**Comment by lucaburgio** [comment]
Added 9368512
