### ISSUE TITLE
[ICON] BBQ

### ISSUE THREAD

**Issue by smessaris** [lucaburgio/iconoir#48]
## Icon Request

* Icon name: BBQ
* Use case: Apartment Feature List for Rentals
* Screenshots of similar icons:
![Screen Shot 2021-06-03 at 15 18 09](https://user-images.githubusercontent.com/61061455/120643565-ffb66900-c47e-11eb-8792-c005a6086171.png)

**Comment by lucaburgio** [comment]
Added 9368512
