### ISSUE TITLE
[FEAT] React Native (Universal) Support

### ISSUE THREAD

**Issue by du5rte** [lucaburgio/iconoir#49]
React native doesn't support normal `svg` elements. Instead they have to be imported from [react-native-svg](react-native-svg) compatibility layer for ios, android and web. SVGR supports it by simply passing the `native` flag.

Happy to contribute if it's something you would like to support ✌️

```
{
  "native": true,
  "typescript": true,
  "expandProps": "end",
}
```

**Comment by lucaburgio** [comment]
@PianoManDanDan @paescuj Any idea to support this?

**Comment by paescuj** [comment]
As @du5rte already mentioned, we can easely build the components for React Native with the `native: true` flag from SVGR. The question is where to place the generated files (maybe even in a separate package)? What do you think @PianoManDanDan?

**Comment by PianoManDanDan** [comment]
As @paescuj said, the biggest question is where to put the generated files. At the moment, my gut is saying to create a separate package called `iconoir-react-native` or something similar. That has the benefit of reducing package sizes for the end user, as well as keeping a clear distinction between React JS and React Native components. However, it will come at the cost of doubling work for updating the packages, as well as essentially copy-pasting the set up we already have. I'll try and have a play around with it if I have some time tomorrow evening and get back to you. Any other suggestions on what we could do are more than welcome 😃

**Comment by lucaburgio** [comment]
Totally agree to have a separate package called `iconoir-react-native`.
From the other side, I also understand and agree that doubling the work to update the package is not ideal.
Keep us updated! 🙏🏻

**Comment by paescuj** [comment]
@PianoManDanDan I feel the same - the best thing would be to put it in a separate package! Any downsides to put the build script outside of the two packages?

**Comment by PianoManDanDan** [comment]
The only downside I can think of off the top of my head is if building one would build the other. If you run the build script from one package it shouldn't affect the other at all in my opinion. We could fairly easily get around that by setting up some arguments for the `build.js` file and passing those in to the packages' npm scripts though

**Comment by du5rte** [comment]
react-native-svg now works on web too you might be able to just have in on place, also great for universal apps, either one would be great. Web users trying to support `react-native-web` could still import `iconoir-react-native` for universal support.
