### ISSUE TITLE
[ICON] arrow with box

### ISSUE THREAD

**Issue by PCNSIROJ** [lucaburgio/iconoir#51]
## Icon Request

* Icon name: arrow with box
* Use case: login or logout
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/62823767/121766954-9372ee00-cb7f-11eb-8850-8bb40222443f.png)

**Comment by lucaburgio** [comment]
These icons already exist. Take a look at `log-in`, `log-out`, and `log-denied`.
