### ISSUE TITLE
[FEAT] An npm package with raw icons for any kind of project

### ISSUE THREAD

**Issue by gawlk** [lucaburgio/iconoir#61]
**Is your feature request related to a problem? Please describe.**

Currently there is no package to use those beautiful icons, the only is to either put them inside the project by hand (annoying) or use the css link (huge)

**Describe the solution you'd like**

Same as the React package but with much less work to do. Just create a package with all the svg-s like the heroicons package does

**Describe alternatives you've considered**

> either put them inside the project by hand (annoying) or use the css link (huge)

**Additional context**

None

**Comment by lucaburgio** [comment]
@paescuj Yes sure! Thank you Pascal!

@gawlk Could you help us to better understand the need? I see that heroicons has 2 npm libraries, `react` and `vue`. But I can't see anything like you described.

**Comment by gawlk** [comment]
@lucaburgio Sure ! Here it is https://www.npmjs.com/package/heroicons
