### ISSUE TITLE
Icons in figma file do not scale properly.

### ISSUE THREAD

**Issue by NotAnmol** [lucaburgio/iconoir#79]
A lot of icons present in the Figma File in the community does not scale properly. When inspecting further we found out constraints of many icons are marked as `Left` Horizontally and `Top` Vertically where they should be marked to `Scale` both horizontally and vertically.

## Step to reproduce

*Try to resize icons, icons mainly in Actions, Audio, Food, Gestures, Maps, Other, Transport will distort.*

### Actual behavior
Icons should have scaled properly just like other icons

## Additional info or screenshots

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/59761332/127340584-15e37584-3e58-4994-9d4a-e7edcf7ac6ba.png">
First icons scales perfectly. Second icon is what distorted icons looks like they do not scale only the frame changes.

**Comment by lucaburgio** [comment]
Changed all the properties to `Scale`.

Anyway, FYI, the scale is K in Figma and the icons were already scaling correctly. What you are using is a manual resize with V (move), which is not a proper scale.
