### ISSUE TITLE
CDN returns 404

### ISSUE THREAD

**Issue by kawarimidoll** [lucaburgio/iconoir#80]
## Prerequisites

* Version: v4.4
* Are you running from source/master: not relevant
* Are you using a released build: yes
* Operating system: macOS 11.5
* Bits:

## Step to reproduce

I copied the code to import from README, but this does not works.
CDN returns 404.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>iconoir</title>
    <link
      href="https://cdn.jsdelivr.net/gh/lucaburgio/iconoir@4.4/css/iconoir.css"
      rel="stylesheet"
      type="text/css"
    />
  </head>
  <body>
    <i class="iconoir-hand-brake"></i>
  </body>
</html>
```

## Any message or error

Access to: https://cdn.jsdelivr.net/gh/lucaburgio/iconoir@4.4/css/iconoir.css
The message is: `Couldn't find the requested file /css/iconoir.css in lucaburgio/iconoir.`

## Additional info or screenshots

![iconoir404](https://user-images.githubusercontent.com/8146876/127627802-32cd28f0-0448-4e69-a449-815f8dcdc7c5.png)

**Comment by jimaek** [comment]
Looks like the css folder wasnt tagged in 4.4 https://github.com/lucaburgio/iconoir/tree/v4.4

**Comment by lucaburgio** [comment]
@Wiwaltill should we add a 4.4.1?

**Comment by Wiwaltill** [comment]
@lucaburgio We just need to replace @4.4 with @master.

**Comment by Wiwaltill** [comment]
https://cdn.jsdelivr.net/gh/lucaburgio/iconoir@master/css/iconoir.css

**Comment by kawarimidoll** [comment]
Sorry for my late reply.
The URL you recommended is works. Thank you.
